Correct #21 so targetHeatingCoolingState works properly
PJCzx/homebridge-thermostat pull request #22
Opened 2017-05-01 12:15 UTC by paullj1

2017-05-03 06:41 UTC, PJCzx requested changes
You may either keep the retrocompatibility with a property and send either the old valu or directly url: this.apiroute + '/targetHeatingCoolingState/' + value instead of testing value to define an action witch will always be the same value :)

2017-05-03 10:52 UTC, paullj1 commented
I guess I'm still a little confused.  You said that both:
* `apiroute + "/off"`
* `apiroute + "/targetHeatingCoolingState/0"`

worked previously, but I don't see how that's possible.  In any case, I'm not sure how to support both without an additional option passed in by the application.  Is this what you were looking for?

2017-05-10 20:27 UTC, PJCzx approved these changes

2017-05-10 20:28 UTC, PJCzx approved these changes

2017-05-10 20:28 UTC, merged

2017-05-10 20:29 UTC, PJCzx commented
Thx @paullj1 for your work :)